# Generated by Django 2.2 on 2019-04-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='rank',
            field=models.CharField(max_length=254),
        ),
    ]
